/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import javax.swing.DefaultComboBoxModel;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;


import Models.User;
import ConecctionDB.MongoDBConnection;
import Controllers.UserController;

 

public class Register extends javax.swing.JFrame {
    private MongoDBConnection mongoConnection = new MongoDBConnection();
    private UserController userController;
    
    
    private String[] typesUser = {"C.C", "T.I"};
    
    public Register() {
        initComponents();
        setLocationRelativeTo(null);    
        setResizable(false); // Hacer que la ventana no sea redimensionable
        SetTypesUser();
        
        mongoConnection.connect();
        userController = new UserController(mongoConnection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        RegisterButton2 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        LoginButton2 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        TypeDocument = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel38.setFont(new java.awt.Font("FiraCode Nerd Font Mono SemBd", 0, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Register");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 50));

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Email");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Last Name");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setForeground(new java.awt.Color(0, 0, 0));
        Name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel3.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, 30));

        jLabel55.setFont(new java.awt.Font("FiraCode Nerd Font Med", 0, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/favicon.png"))); // NOI18N
        jLabel55.setText("My Hotel");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 200, 50));

        LastName.setBackground(new java.awt.Color(255, 255, 255));
        LastName.setForeground(new java.awt.Color(0, 0, 0));
        LastName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        jPanel3.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 180, 30));

        Address.setBackground(new java.awt.Color(255, 255, 255));
        Address.setForeground(new java.awt.Color(0, 0, 0));
        Address.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        jPanel3.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, 30));

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel3.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 180, 30));

        jLabel41.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("ID");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Name");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("City");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Type document");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setForeground(new java.awt.Color(0, 0, 0));
        ID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel3.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 30));

        jLabel45.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Phone");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Password");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Confirm Password");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 319, -1, 20));

        jLabel48.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Address");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        City.setBackground(new java.awt.Color(255, 255, 255));
        City.setForeground(new java.awt.Color(0, 0, 0));
        City.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });
        jPanel3.add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, 30));

        Phone.setBackground(new java.awt.Color(255, 255, 255));
        Phone.setForeground(new java.awt.Color(0, 0, 0));
        Phone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        jPanel3.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 180, 30));

        RegisterButton2.setBackground(new java.awt.Color(0, 153, 255));
        RegisterButton2.setFont(new java.awt.Font("FiraCode Nerd Font Propo Med", 0, 14)); // NOI18N
        RegisterButton2.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton2.setText("Register");
        RegisterButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RegisterButton2FocusGained(evt);
            }
        });
        RegisterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(RegisterButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, 40));

        jLabel49.setFont(new java.awt.Font("FiraCode Nerd Font Propo", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("You have an account? ");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        LoginButton2.setBackground(new java.awt.Color(0, 153, 255));
        LoginButton2.setFont(new java.awt.Font("FiraCode Nerd Font Mono SemBd", 0, 14)); // NOI18N
        LoginButton2.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton2.setText("Login");
        LoginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(LoginButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 80, 20));

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("FiraCode Nerd Font Ret", 0, 36)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("My Hotel");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 260, -1));

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/logo.png"))); // NOI18N
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 260, -1));

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/logo.png"))); // NOI18N
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 260, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/city.png"))); // NOI18N
        jLabel53.setText("jLabel3");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 260, 500));

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 180, 30));

        ConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 180, 30));

        TypeDocument.setBackground(new java.awt.Color(255, 255, 255));
        TypeDocument.setForeground(new java.awt.Color(0, 0, 0));
        TypeDocument.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"T.I","C.C"}));
        TypeDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeDocumentActionPerformed(evt);
            }
        });
        jPanel3.add(TypeDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 30));

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/logo.png"))); // NOI18N
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void RegisterButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RegisterButton2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButton2FocusGained

    private void RegisterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButton2ActionPerformed
        
        
        if (!mongoConnection.isConexionExitosa()) {
            showMessageDialog(null, "Data Base is not connected.", "Error", ERROR_MESSAGE);
            return;
        }

        if (!registerHandler()) {
            showMessageDialog(null, "All fields are required", "Error", ERROR_MESSAGE);
            return;
        }

        if (!PasswordHandler()) {
            showMessageDialog(null, "Passwords do not match.", "Error", ERROR_MESSAGE);
            return;
        }

        if(!userController.checkUserExistence(Email.getText())){
            if (registerUser()) {
                showMessageDialog(null, "User created successfully.", "Success", INFORMATION_MESSAGE);
                mongoConnection.close();
                disposeAndShowLoginWindow();
            } else {
                showMessageDialog(null, "The user can't be created", "Error", ERROR_MESSAGE);
            }
        }else {
                showMessageDialog(null, "The user already exists", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegisterButton2ActionPerformed

    private void LoginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton2ActionPerformed
        mongoConnection.close();
        disposeAndShowLoginWindow();
    }//GEN-LAST:event_LoginButton2ActionPerformed

    private void TypeDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeDocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeDocumentActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void SetTypesUser(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(typesUser);
        TypeDocument.setModel(model);
    }
    
    private boolean PasswordHandler(){
        String password = new String(Password.getPassword());
        String confirmPassword = new String(ConfirmPassword.getPassword());
        if (!password.equals(confirmPassword)) {
            return false;
        }
        return true;
    }
    
    private boolean registerHandler() {
        // Obtener el contenido de todos los campos de texto
        String id = ID.getText();
        String name = Name.getText();
        String lastName = LastName.getText();
        String email = Email.getText();
        String address = Address.getText();
        String city = City.getText();
        String phone = Phone.getText();
        String password = new String(Password.getPassword());
        String confirmPassword = new String(ConfirmPassword.getPassword());

        // Verificar que todos los campos obligatorios estén completos
        if (id.isEmpty() || name.isEmpty() || lastName.isEmpty() || email.isEmpty() ||
            address.isEmpty() || city.isEmpty() || phone.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
            // Mostrar un mensaje de error si falta algún campo
            return false;
        }
        // Si todos los campos están completos y las contraseñas coinciden, devolver true
        return true;
    }
    
    private boolean registerUser(){

        userController = new UserController(mongoConnection);
                
        String typeDocument = TypeDocument.getSelectedItem().toString();
        String id = ID.getText();
        String name = Name.getText();
        String lastName = LastName.getText();
        String email = Email.getText();
        String address = Address.getText();
        String city = City.getText();
        String phone = Phone.getText();
        String password = new String(Password.getPassword());
        
        User user = new User(typeDocument, 
                            id, 
                            name, 
                            lastName, 
                            email, 
                            address, 
                            city, 
                            phone, 
                            password, 
                            "User");
        
        if(userController.Register(user)){
           return true; 
        }else{
           return false;
        }
        
    }
    
    private void disposeAndShowLoginWindow(){
        dispose();
        Login loginView = new Login();
        loginView.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField City;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField LastName;
    private javax.swing.JButton LoginButton2;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JButton RegisterButton2;
    private javax.swing.JComboBox<String> TypeDocument;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
