/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Panels;

import Controllers.UserController;
import Models.User;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Administrator
 */
public class RegisterPanel extends javax.swing.JPanel {

    private UserController userController = new UserController();
    private String[] typesUser = {"C.C", "T.I"};
    
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLabel = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        TypeDocument = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel47 = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JPasswordField();
        RegisterButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(560, 440));
        setPreferredSize(new java.awt.Dimension(560, 440));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLabel.setFont(new java.awt.Font("FiraCode Nerd Font Mono SemBd", 0, 36)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(0, 0, 0));
        LoginLabel.setText("Register");
        add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 50));

        jLabel44.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Type document");
        add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        TypeDocument.setBackground(new java.awt.Color(255, 255, 255));
        TypeDocument.setForeground(new java.awt.Color(0, 0, 0));
        TypeDocument.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"T.I","C.C"}));
        TypeDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeDocumentActionPerformed(evt);
            }
        });
        add(TypeDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 30));

        jLabel41.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("ID");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setForeground(new java.awt.Color(0, 0, 0));
        ID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 30));

        jLabel42.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Name");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setForeground(new java.awt.Color(0, 0, 0));
        Name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Last Name");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        LastName.setBackground(new java.awt.Color(255, 255, 255));
        LastName.setForeground(new java.awt.Color(0, 0, 0));
        LastName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 180, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Email");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 30));

        jLabel48.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Address");
        add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        Address.setBackground(new java.awt.Color(255, 255, 255));
        Address.setForeground(new java.awt.Color(0, 0, 0));
        Address.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 180, 30));

        jLabel43.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("City");
        add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        City.setBackground(new java.awt.Color(255, 255, 255));
        City.setForeground(new java.awt.Color(0, 0, 0));
        City.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });
        add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, 30));

        jLabel45.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Phone");
        add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        Phone.setBackground(new java.awt.Color(255, 255, 255));
        Phone.setForeground(new java.awt.Color(0, 0, 0));
        Phone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 180, 30));

        jLabel46.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Password");
        add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, 30));

        jLabel47.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Confirm Password");
        add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, 20));

        ConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 180, 30));

        RegisterButton2.setBackground(new java.awt.Color(0, 153, 255));
        RegisterButton2.setFont(new java.awt.Font("FiraCode Nerd Font Propo Med", 0, 14)); // NOI18N
        RegisterButton2.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton2.setText("Register");
        RegisterButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RegisterButton2FocusGained(evt);
            }
        });
        RegisterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButton2ActionPerformed(evt);
            }
        });
        add(RegisterButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void TypeDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeDocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeDocumentActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void RegisterButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RegisterButton2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButton2FocusGained

    private void RegisterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButton2ActionPerformed
        if (!registerHandler()) {
            showMessageDialog(null, "All fields are required", "Error", ERROR_MESSAGE);
            return;
        }

        if (!PasswordHandler()) {
            showMessageDialog(null, "Passwords do not match.", "Error", ERROR_MESSAGE);
            return;
        }

        if(!userController.userExist(Email.getText())){
            if (registerUser()) {
                showMessageDialog(null, "User created successfully.", "Success", INFORMATION_MESSAGE);
                return;
            } else {
                showMessageDialog(null, "The user can't be created", "Error", ERROR_MESSAGE);
            }
        }else {
            showMessageDialog(null, "The user already exists", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegisterButton2ActionPerformed

    private void SetTypesUser(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(typesUser);
        TypeDocument.setModel(model);
    }
    
    private boolean PasswordHandler(){
        String password = new String(Password.getPassword());
        String confirmPassword = new String(ConfirmPassword.getPassword());
        if (!password.equals(confirmPassword)) {
            return false;
        }
        return true;
    }
    
    private boolean registerHandler() {
        // Obtener el contenido de todos los campos de texto
        String id = ID.getText();
        String name = Name.getText();
        String lastName = LastName.getText();
        String email = Email.getText();
        String address = Address.getText();
        String city = City.getText();
        String phone = Phone.getText();
        String password = new String(Password.getPassword());
        String confirmPassword = new String(ConfirmPassword.getPassword());

        // Verificar que todos los campos obligatorios estén completos
        if (id.isEmpty() || name.isEmpty() || lastName.isEmpty() || email.isEmpty() ||
            address.isEmpty() || city.isEmpty() || phone.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
            // Mostrar un mensaje de error si falta algún campo
            return false;
        }
        // Si todos los campos están completos y las contraseñas coinciden, devolver true
        return true;
    }
    
    private boolean registerUser(){

        
                
        String typeDocument = TypeDocument.getSelectedItem().toString();
        String id = ID.getText();
        String name = Name.getText();
        String lastName = LastName.getText();
        String email = Email.getText();
        String address = Address.getText();
        String city = City.getText();
        String phone = Phone.getText();
        String password = new String(Password.getPassword());
        
        User user = new User(typeDocument, 
                            id, 
                            name, 
                            lastName, 
                            email, 
                            address, 
                            city, 
                            phone, 
                            password, 
                            "User");
        
        if(userController.register(user)){
           return true; 
        }else{
           return false;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField City;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JButton RegisterButton2;
    private javax.swing.JComboBox<String> TypeDocument;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    // End of variables declaration//GEN-END:variables
}
