/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Panels;

import javax.swing.table.DefaultTableModel;

import Controllers.RoomController;
import Models.User;
import Views.Panels.UpRoom;
import Views.Home;
/**
 *
 * @author Administrator
 */
public class RoomsPanel extends javax.swing.JPanel {
    private RoomController roomController = new RoomController();
    private User user;
    private boolean isAdmin = false;
    public RoomsPanel(User user) {
        initComponents();
        this.user = user;
        
        if(user.getTypeUser().equals("Admin")){
            this.isAdmin = true; // Asignar true a isAdmin si el usuario es un administrador
        } else {
            this.isAdmin = false; // Asignar false a isAdmin si el usuario no es un administrador
        }

        LoadRooms();
        loadOptions();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Create = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(550, 420));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 420));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Create.setBackground(new java.awt.Color(18, 90, 173));
        Create.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("Create");
        Create.setBorderPainted(false);
        Create.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        Update.setBackground(new java.awt.Color(18, 90, 173));
        Update.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.setBorderPainted(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        Delete.setBackground(new java.awt.Color(18, 90, 173));
        Delete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.setBorderPainted(false);
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Number", "Type", "Capacity", "Price/Night"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        if(isAdmin){
            Home.ShowJPanel(new UpRoom(this.user));
            return;
        }
        
        if (jTable1.getSelectedRow() > -1) {
            try {
                String roomId = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                Home.ShowJPanel(new Booking(roomController.getRoomByID(roomId), user));
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "You must select one or more Rooms  b.\n", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
            

        
    }//GEN-LAST:event_CreateActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            try {
                String roomId = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                Home.ShowJPanel(new UpRoom(this.user, roomController.getRoomByID(roomId)));
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "You must select one or more Rooms to update.\n", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRows().length < 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "You must select one or more Rooms to delete.\n", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i : jTable1.getSelectedRows()) {
                try {
                    roomController.delete((String) jTable1.getValueAt(i, 0));
                    model.removeRow(i);
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed
    
    private void loadOptions(){
        if(!this.isAdmin){
           Delete.setVisible(false);
           Update.setVisible(false);
           Create.setText("Book");
        }
    }
    
    private void LoadRooms() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            roomController.list().forEach((u) -> model.addRow(new Object[]{u.getId(), u.getNumber(), u.getType(), u.getCapacity(),u.getPriceNight()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
