/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Users;

import Models.User;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

public class AdminView extends javax.swing.JFrame {

    private User user;
    public AdminView(User user) {
        initComponents();
        this.user = user;
        
        AdminID.setText(user.getId());
        AdminName.setText(user.getName());
        AdminEmail.setText(user.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminID = new javax.swing.JLabel();
        AdminName = new javax.swing.JLabel();
        AdminEmail = new javax.swing.JLabel();
        TypeUser3 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        BookingsUser = new javax.swing.JMenu();
        BookingManager = new javax.swing.JMenuItem();
        History = new javax.swing.JMenuItem();
        Rooms = new javax.swing.JMenu();
        AllRooms = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminID.setBackground(new java.awt.Color(0, 0, 0));
        AdminID.setForeground(new java.awt.Color(0, 0, 0));
        AdminID.setText("Admin");
        jPanel1.add(AdminID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        AdminName.setBackground(new java.awt.Color(0, 0, 0));
        AdminName.setForeground(new java.awt.Color(0, 0, 0));
        AdminName.setText("Admin");
        jPanel1.add(AdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        AdminEmail.setBackground(new java.awt.Color(0, 0, 0));
        AdminEmail.setForeground(new java.awt.Color(0, 0, 0));
        AdminEmail.setText("Admin");
        jPanel1.add(AdminEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 20));

        TypeUser3.setBackground(new java.awt.Color(0, 0, 0));
        TypeUser3.setForeground(new java.awt.Color(0, 0, 0));
        TypeUser3.setText("Admin");
        jPanel1.add(TypeUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        Menu.setBackground(new java.awt.Color(75, 202, 242));
        Menu.setForeground(new java.awt.Color(0, 0, 0));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setMargin(new java.awt.Insets(10, 10, 10, 10));
        Menu.setSelectionModel(null);

        BookingsUser.setText("Bookings");
        BookingsUser.setToolTipText("");

        BookingManager.setText("Bookings Manager");
        BookingManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingManagerActionPerformed(evt);
            }
        });
        BookingsUser.add(BookingManager);

        History.setText("History");
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });
        BookingsUser.add(History);

        Menu.add(BookingsUser);

        Rooms.setText("Rooms");

        AllRooms.setText("All Rooms");
        AllRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRoomsActionPerformed(evt);
            }
        });
        Rooms.add(AllRooms);

        Menu.add(Rooms);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingManagerActionPerformed
        // TODO add your handling code here:
        showMessageDialog(null, "Boking Manager", "Success", INFORMATION_MESSAGE);
    }//GEN-LAST:event_BookingManagerActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        showMessageDialog(null, "History", "Success", INFORMATION_MESSAGE);
    }//GEN-LAST:event_HistoryActionPerformed

    private void AllRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRoomsActionPerformed

        showMessageDialog(null, "Rooms", "Success", INFORMATION_MESSAGE);
    }//GEN-LAST:event_AllRoomsActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminEmail;
    private javax.swing.JLabel AdminID;
    private javax.swing.JLabel AdminName;
    private javax.swing.JMenuItem AllRooms;
    private javax.swing.JMenuItem BookingManager;
    private javax.swing.JMenu BookingsUser;
    private javax.swing.JMenuItem History;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Rooms;
    private javax.swing.JLabel TypeUser3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
