/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Users;

import Views.Login;

import Models.User;




/**
 *
 * @author Administrator
 */
public class HomeView extends javax.swing.JFrame {

    private User user;
    public HomeView(User user) {
        initComponents();
        setLocationRelativeTo(null); 
        
        this.user = user;
        
        setText();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LogoutLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        ImageUser = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();
        NameLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        LogoutLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutLabel.setText("Logout");
        LogoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 100, 40));

        jPanel3.setBackground(new java.awt.Color(6, 134, 190));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        WelcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("Welcome");
        jPanel1.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 260, 30));

        UserName.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserName.setText("jLabel1");
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 230, 100));

        ImageUser.setForeground(new java.awt.Color(0, 0, 0));
        ImageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/logo.png"))); // NOI18N
        jPanel1.add(ImageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 290, 190));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/city.png"))); // NOI18N
        BackgroundImage.setText("jLabel3");
        jPanel1.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 290, 500));

        NameLogo.setFont(new java.awt.Font("FiraCode Nerd Font Med", 0, 24)); // NOI18N
        NameLogo.setForeground(new java.awt.Color(0, 0, 0));
        NameLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/favicon.png"))); // NOI18N
        NameLogo.setText("My Hotel");
        jPanel1.add(NameLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, 50));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("FiraCode Nerd Font", 1, 18)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(51, 51, 51));
        jTextPane1.setText("Welcome to My Hotel, where luxury and comfort merge to offer you an unparalleled experience. From our elegant guest rooms to our world-class restaurants and world-class spa, every detail is designed for your ultimate enjoyment. Let our expert staff provide impeccable service during your stay, creating memories that will last long after you leave.");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 450, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     private void setText() {
        UserName.setText(user.getTypeUser());
        WelcomeLabel.setText("Welcome! " + user.getName());
        
       
    }
    private void disposeAndShowLogin(){
        dispose();
        
        Login view = new Login();
        
        view.setVisible(true);
    }
    
    private void LogoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLabelMouseClicked
        disposeAndShowLogin();
    }//GEN-LAST:event_LogoutLabelMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel ImageUser;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JLabel NameLogo;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
