/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Users;

import ConecctionDB.MongoDBConnection;
import Controllers.UserController;

import Models.User;
import Views.Login;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

public class UserView1 extends javax.swing.JFrame {
    private MongoDBConnection connection = new MongoDBConnection();
    private UserController userController;
    
    private User user;
    
    public UserView1(String email) {
        initComponents();
        
        setLocationRelativeTo(null); 
        setResizable(false); // Hacer que la ventana no sea redimensionable 
        
        connection.connect();
        userController = new UserController(connection);
        
        userController.getUser(email);
        this.user = userController.getLoggedUser();
        
        
        
        
        
        // Add a mouse listener to the Exit label to handle the click event
        Exit.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                disposeAndShowLoginWindow();
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                Exit.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                Exit.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        BookingsUser = new javax.swing.JMenu();
        BookingManager = new javax.swing.JMenuItem();
        History = new javax.swing.JMenuItem();
        Rooms = new javax.swing.JMenu();
        AllRooms = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/klipartz.com (3).png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 260, 160));

        Name.setFont(new java.awt.Font("FiraCode Nerd Font Mono SemBd", 0, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Nombre");
        jPanel4.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 280, 50));

        jLabel22.setFont(new java.awt.Font("FiraCode Nerd Font Mono SemBd", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Welcome");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 280, 50));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/X.png"))); // NOI18N
        Exit.setLabelFor(jLabel20);
        jPanel4.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("FiraCode Nerd Font Mono SemBd", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Logout");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 70, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/city.png"))); // NOI18N
        jLabel16.setText("jLabel3");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 280, 440));

        jLabel1.setFont(new java.awt.Font("FiraCode Nerd Font Med", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/favicon.png"))); // NOI18N
        jLabel1.setText("My Hotel");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jLabel23.setFont(new java.awt.Font("FiraCode Nerd Font Mono SemBd", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Home");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 150, 50));

        Menu.setBackground(new java.awt.Color(75, 202, 242));
        Menu.setForeground(new java.awt.Color(0, 0, 0));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setMargin(new java.awt.Insets(10, 10, 10, 10));
        Menu.setSelectionModel(null);

        BookingsUser.setText("Bookings");
        BookingsUser.setToolTipText("");

        BookingManager.setText("Bookings Manager");
        BookingManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingManagerActionPerformed(evt);
            }
        });
        BookingsUser.add(BookingManager);

        History.setText("History");
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });
        BookingsUser.add(History);

        Menu.add(BookingsUser);

        Rooms.setText("Rooms");

        AllRooms.setText("All Rooms");
        AllRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRoomsActionPerformed(evt);
            }
        });
        Rooms.add(AllRooms);

        Menu.add(Rooms);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookingManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingManagerActionPerformed
        // TODO add your handling code here:
        showMessageDialog(null, "Boking Manager", "Success", INFORMATION_MESSAGE);
    }//GEN-LAST:event_BookingManagerActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        showMessageDialog(null, "History", "Success", INFORMATION_MESSAGE);
    }//GEN-LAST:event_HistoryActionPerformed

    private void AllRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRoomsActionPerformed

        showMessageDialog(null, "Rooms", "Success", INFORMATION_MESSAGE);
    }//GEN-LAST:event_AllRoomsActionPerformed

    private void disposeAndShowLoginWindow(){
        dispose();
        //Login view = new Login();
        //view.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AllRooms;
    private javax.swing.JMenuItem BookingManager;
    private javax.swing.JMenu BookingsUser;
    private javax.swing.JLabel Exit;
    private javax.swing.JMenuItem History;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel Name;
    private javax.swing.JMenu Rooms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
